import type { EffectiveAppearanceMode, ThemeOption } from './types'
import { mixHex, toRgba } from './color-utils'

export function applyPaletteTheme(root: HTMLElement, appearanceMode: EffectiveAppearanceMode, selectedTheme: ThemeOption): void {
  const darkBase = mixHex('#050d1d', selectedTheme.primaryStrong, 0.25)
  const darkSoft = mixHex('#0b1b37', selectedTheme.primary, 0.3)
  const darkCard = mixHex('#0b1a34', selectedTheme.primaryStrong, 0.24)
  const darkLine = mixHex('#27456f', selectedTheme.primary, 0.35)
  const darkSurfaceStrong = mixHex('#08172f', selectedTheme.primaryStrong, 0.22)
  const darkSurfaceMuted = mixHex('#0d1e38', selectedTheme.primaryStrong, 0.24)
  const darkSurfaceAlt = mixHex('#143563', selectedTheme.primary, 0.18)
  const darkSurfaceHover = mixHex('#255793', selectedTheme.primary, 0.22)
  const darkTableHead = mixHex('#0f2a4b', selectedTheme.primaryStrong, 0.24)
  const darkGroupJob = mixHex('#16365f', selectedTheme.primary, 0.24)
  const darkGroupNormal = mixHex('#2a284f', selectedTheme.primaryStrong, 0.18)
  const darkGroupHover = mixHex('#214a7a', selectedTheme.primary, 0.24)
  const darkTimelineColumn = mixHex('#09162a', selectedTheme.primaryStrong, 0.2)
  const darkTimelineEvent = mixHex('#3b82f6', selectedTheme.primary, 0.75)
  const darkNoticeBg = mixHex('#112845', selectedTheme.primaryStrong, 0.34)
  const darkNoticeText = mixHex('#b7d5ff', selectedTheme.accent, 0.18)
  const darkErrorBg = mixHex('#3a1822', selectedTheme.primaryStrong, 0.2)
  const darkErrorText = mixHex('#ffc3cf', selectedTheme.accent, 0.08)
  const darkDangerBg = mixHex('#6a2236', selectedTheme.primaryStrong, 0.16)
  const darkDangerBorder = mixHex('#8a3350', selectedTheme.primaryStrong, 0.1)
  const darkDangerText = mixHex('#ffd7de', selectedTheme.accent, 0.06)

  const lightBase = mixHex('#f4f8ff', selectedTheme.primary, 0.08)
  const lightSoft = mixHex('#e7efff', selectedTheme.accent, 0.12)
  const lightCard = mixHex('#ffffff', selectedTheme.primary, 0.04)
  const lightLine = mixHex('#bfd0ea', selectedTheme.primary, 0.36)
  const lightSurfaceStrong = mixHex('#ffffff', selectedTheme.primary, 0.08)
  const lightSurfaceMuted = mixHex('#edf3ff', selectedTheme.primary, 0.12)
  const lightSurfaceAlt = mixHex('#d7e6ff', selectedTheme.primary, 0.25)
  const lightSurfaceHover = mixHex('#c9ddff', selectedTheme.primary, 0.3)
  const lightTableHead = mixHex('#e8f1ff', selectedTheme.primary, 0.2)
  const lightGroupJob = mixHex('#dcecff', selectedTheme.primary, 0.28)
  const lightGroupNormal = mixHex('#e7e8ff', selectedTheme.primaryStrong, 0.15)
  const lightGroupHover = mixHex('#cfe2ff', selectedTheme.primary, 0.32)
  const lightTimelineColumn = mixHex('#f5f9ff', selectedTheme.primary, 0.1)
  const lightTimelineEvent = mixHex('#3e78d5', selectedTheme.primary, 0.7)
  const lightNoticeBg = mixHex('#e6f0ff', selectedTheme.primary, 0.18)
  const lightNoticeText = mixHex('#2d4f80', selectedTheme.primaryStrong, 0.22)
  const lightErrorBg = mixHex('#ffe7ed', selectedTheme.primaryStrong, 0.1)
  const lightErrorText = mixHex('#943651', selectedTheme.primaryStrong, 0.2)
  const lightDangerBg = mixHex('#ffe7ed', selectedTheme.primaryStrong, 0.12)
  const lightDangerBorder = mixHex('#d88ba2', selectedTheme.primaryStrong, 0.18)
  const lightDangerText = mixHex('#8f2f4a', selectedTheme.primaryStrong, 0.24)
  const focusRing = mixHex('#5b9bff', selectedTheme.accent, 0.58)

  root.style.setProperty('--primary', selectedTheme.primary)
  root.style.setProperty('--primary-strong', selectedTheme.primaryStrong)
  root.style.setProperty('--accent', selectedTheme.accent)
  root.style.setProperty('--btn-primary-end', selectedTheme.primaryStrong)
  root.style.setProperty('--btn-primary-shadow', toRgba(selectedTheme.primary, 0.42))
  root.style.setProperty('--floating-switch-shadow', `0 14px 32px ${toRgba(selectedTheme.primaryStrong, 0.42)}`)
  root.style.setProperty('--floating-switch-shadow-hover', `0 18px 36px ${toRgba(selectedTheme.primaryStrong, 0.5)}`)
  root.style.setProperty('--btn-primary-text', '#ffffff')
  root.style.setProperty('--focus-ring', focusRing)
  root.style.setProperty('--focus-ring-shadow', toRgba(focusRing, 0.32))
  root.style.setProperty('--bg-glow-primary', toRgba(selectedTheme.primary, 0.28))
  root.style.setProperty('--bg-glow-primary-soft', toRgba(selectedTheme.primary, 0.11))
  root.style.setProperty('--bg-glow-accent', toRgba(selectedTheme.accent, 0.24))
  root.style.setProperty('--bg-glow-accent-soft', toRgba(selectedTheme.accent, 0.09))

  if (appearanceMode === 'dark') {
    root.style.setProperty('--hero-eyebrow-color', mixHex('#d6e8ff', selectedTheme.accent, 0.18))
    root.style.setProperty('--bg-base', darkBase)
    root.style.setProperty('--bg-soft', darkSoft)
    root.style.setProperty('--bg-card', toRgba(darkCard, 0.82))
    root.style.setProperty('--line', darkLine)
    root.style.setProperty('--text-main', mixHex('#e9f0ff', selectedTheme.accent, 0.06))
    root.style.setProperty('--text-sub', mixHex('#9fb2d9', selectedTheme.accent, 0.16))
    root.style.setProperty('--surface-elevated', toRgba(darkSoft, 0.72))
    root.style.setProperty('--surface-elevated-soft', toRgba(darkSoft, 0.48))
    root.style.setProperty('--surface-strong', toRgba(darkSurfaceStrong, 0.86))
    root.style.setProperty('--surface-muted', toRgba(darkSurfaceMuted, 0.82))
    root.style.setProperty('--surface-alt', toRgba(darkSurfaceAlt, 0.42))
    root.style.setProperty('--surface-hover', toRgba(darkSurfaceHover, 0.34))
    root.style.setProperty('--surface-overlay', toRgba(darkSurfaceStrong, 0.58))
    root.style.setProperty('--overlay-backdrop', 'rgba(2, 9, 23, 0.72)')
    root.style.setProperty('--btn-soft-bg', '#12284a')
    root.style.setProperty('--btn-soft-text', '#d6e5ff')
    root.style.setProperty('--btn-soft-border', '#2f4f80')
    root.style.setProperty('--btn-soft-hover-bg', toRgba(darkSurfaceAlt, 0.58))
    root.style.setProperty('--btn-danger-bg', darkDangerBg)
    root.style.setProperty('--btn-danger-border', darkDangerBorder)
    root.style.setProperty('--btn-danger-text', darkDangerText)
    root.style.setProperty('--panel-border', toRgba(darkLine, 0.34))
    root.style.setProperty('--panel-shadow', '0 20px 45px rgba(2, 8, 24, 0.45)')
    root.style.setProperty('--modal-bg', '#0a1f3c')
    root.style.setProperty('--modal-border', '#2e4f80')
    root.style.setProperty('--modal-text-sub', '#b7caec')
    root.style.setProperty('--notice-bg', darkNoticeBg)
    root.style.setProperty('--notice-text', darkNoticeText)
    root.style.setProperty('--error-bg', darkErrorBg)
    root.style.setProperty('--error-text', darkErrorText)
    root.style.setProperty('--table-head-bg', toRgba(darkTableHead, 0.96))
    root.style.setProperty('--group-sticky-bg', toRgba(darkTableHead, 0.95))
    root.style.setProperty('--group-job-bg', toRgba(darkGroupJob, 0.96))
    root.style.setProperty('--group-normal-bg', toRgba(darkGroupNormal, 0.96))
    root.style.setProperty('--group-hover-bg', toRgba(darkGroupHover, 0.96))
    root.style.setProperty('--state-ok-bg', 'rgba(16, 80, 56, 0.78)')
    root.style.setProperty('--state-ok-text', '#9ef5ca')
    root.style.setProperty('--state-ng-bg', 'rgba(88, 32, 32, 0.78)')
    root.style.setProperty('--state-ng-text', '#ffc1b2')
    root.style.setProperty('--state-unknown-bg', 'rgba(56, 70, 95, 0.78)')
    root.style.setProperty('--state-unknown-text', '#c3d1f2')
    root.style.setProperty('--state-running-bg', 'rgba(103, 74, 18, 0.78)')
    root.style.setProperty('--state-running-text', '#ffe08f')
    root.style.setProperty('--state-unreachable-bg', 'rgba(92, 38, 55, 0.78)')
    root.style.setProperty('--state-unreachable-text', '#ffc0d4')
    root.style.setProperty('--state-total-bg', 'rgba(36, 62, 101, 0.78)')
    root.style.setProperty('--state-total-text', '#d1e3ff')
    root.style.setProperty('--chart-axis-line', toRgba(mixHex('#4f72aa', selectedTheme.primary, 0.2), 0.45))
    root.style.setProperty('--chart-axis-text', mixHex('#8fa6cf', selectedTheme.accent, 0.2))
    root.style.setProperty('--chart-grid-line', toRgba(mixHex('#7e9fd3', selectedTheme.primary, 0.2), 0.2))
    root.style.setProperty('--chart-plot-bg', toRgba(darkSurfaceStrong, 0.76))
    root.style.setProperty('--chart-avg-line', 'rgba(72, 197, 133, 0.9)')
    root.style.setProperty('--chart-avg-bg', toRgba(darkSurfaceMuted, 0.92))
    root.style.setProperty('--chart-avg-border', 'rgba(72, 197, 133, 0.5)')
    root.style.setProperty('--chart-avg-text', '#82e2b2')
    root.style.setProperty('--chart-bar-bg', mixHex('#4f93ff', selectedTheme.primary, 0.6))
    root.style.setProperty('--chart-bar-shadow', toRgba(mixHex('#2563eb', selectedTheme.primaryStrong, 0.5), 0.32))
    root.style.setProperty('--timeline-axis-line', toRgba(mixHex('#4f72aa', selectedTheme.primary, 0.2), 0.35))
    root.style.setProperty('--timeline-axis-text', mixHex('#8fa6cf', selectedTheme.accent, 0.2))
    root.style.setProperty('--timeline-day-border', toRgba(mixHex('#5575ab', selectedTheme.primary, 0.2), 0.4))
    root.style.setProperty('--timeline-day-title', '#d8e5ff')
    root.style.setProperty('--timeline-day-date', mixHex('#9ad5ff', selectedTheme.accent, 0.3))
    root.style.setProperty('--timeline-column-bg', toRgba(darkTimelineColumn, 0.88))
    root.style.setProperty('--timeline-hour-line', toRgba(mixHex('#4f72aa', selectedTheme.primary, 0.2), 0.32))
    root.style.setProperty('--timeline-event-bg', darkTimelineEvent)
    root.style.setProperty('--timeline-event-text', '#f5f9ff')
    root.style.setProperty('--timeline-event-shadow', toRgba(mixHex('#0f2a56', selectedTheme.primaryStrong, 0.5), 0.42))
    root.style.setProperty('--mobile-nav-bg-start', toRgba(darkBase, 0.86))
    root.style.setProperty('--mobile-nav-bg-end', toRgba(darkSoft, 0.72))
    root.style.setProperty('--mobile-nav-border', toRgba(darkLine, 0.34))
    root.style.setProperty('--mobile-nav-text', '#b5c8eb')
    root.style.setProperty('--mobile-nav-text-active', '#ffffff')
    root.style.setProperty('--mobile-nav-icon-filter', 'brightness(0) saturate(100%) invert(74%) sepia(20%) saturate(376%) hue-rotate(185deg) brightness(94%) contrast(92%)')
    root.style.setProperty('--mobile-nav-icon-active-filter', 'brightness(0) saturate(100%) invert(100%)')
    root.style.setProperty('--header-settings-icon-filter', 'brightness(0) saturate(100%) invert(100%)')
    root.style.setProperty('--mobile-register-bg-start', toRgba(darkSurfaceMuted, 0.9))
    root.style.setProperty('--mobile-register-bg-end', toRgba(darkSurfaceStrong, 0.84))
    root.style.setProperty('--mobile-register-border', toRgba(darkLine, 0.52))
    root.style.setProperty('--mobile-register-active-start', selectedTheme.primary)
    root.style.setProperty('--mobile-register-active-end', mixHex(selectedTheme.accent, selectedTheme.primaryStrong, 0.6))
    root.style.setProperty('--mobile-register-active-shadow', toRgba(selectedTheme.primary, 0.32))
    root.style.setProperty('--scrollbar-track', toRgba(darkSurfaceMuted, 0.56))
    root.style.setProperty('--scrollbar-thumb', toRgba(mixHex('#7faef8', selectedTheme.primary, 0.45), 0.84))
    root.style.setProperty('--scrollbar-thumb-hover', toRgba(mixHex('#9ec3ff', selectedTheme.accent, 0.32), 0.94))
    return
  }

  root.style.setProperty('--bg-base', lightBase)
  root.style.setProperty('--hero-eyebrow-color', mixHex('#2f4f80', selectedTheme.primaryStrong, 0.32))
  root.style.setProperty('--bg-soft', lightSoft)
  root.style.setProperty('--bg-card', toRgba(lightCard, 0.88))
  root.style.setProperty('--line', lightLine)
  root.style.setProperty('--text-main', mixHex('#1a2f55', selectedTheme.primaryStrong, 0.12))
  root.style.setProperty('--text-sub', mixHex('#4f6691', selectedTheme.primaryStrong, 0.2))
  root.style.setProperty('--surface-elevated', toRgba(lightSoft, 0.68))
  root.style.setProperty('--surface-elevated-soft', toRgba(lightSoft, 0.42))
  root.style.setProperty('--surface-strong', toRgba(lightSurfaceStrong, 0.95))
  root.style.setProperty('--surface-muted', toRgba(lightSurfaceMuted, 0.96))
  root.style.setProperty('--surface-alt', toRgba(lightSurfaceAlt, 0.45))
  root.style.setProperty('--surface-hover', toRgba(lightSurfaceHover, 0.52))
  root.style.setProperty('--surface-overlay', toRgba(lightSurfaceMuted, 0.64))
  root.style.setProperty('--overlay-backdrop', 'rgba(15, 36, 69, 0.42)')
  root.style.setProperty('--btn-soft-bg', '#e8f0ff')
  root.style.setProperty('--btn-soft-text', '#274471')
  root.style.setProperty('--btn-soft-border', '#b7ccea')
  root.style.setProperty('--btn-soft-hover-bg', toRgba(lightSurfaceAlt, 0.7))
  root.style.setProperty('--btn-danger-bg', lightDangerBg)
  root.style.setProperty('--btn-danger-border', lightDangerBorder)
  root.style.setProperty('--btn-danger-text', lightDangerText)
  root.style.setProperty('--panel-border', toRgba(lightLine, 0.85))
  root.style.setProperty('--panel-shadow', '0 14px 28px rgba(30, 62, 109, 0.12)')
  root.style.setProperty('--modal-bg', '#f8fbff')
  root.style.setProperty('--modal-border', '#bfd2ef')
  root.style.setProperty('--modal-text-sub', '#5f78a8')
  root.style.setProperty('--notice-bg', lightNoticeBg)
  root.style.setProperty('--notice-text', lightNoticeText)
  root.style.setProperty('--error-bg', lightErrorBg)
  root.style.setProperty('--error-text', lightErrorText)
  root.style.setProperty('--table-head-bg', toRgba(lightTableHead, 0.98))
  root.style.setProperty('--group-sticky-bg', toRgba(lightTableHead, 0.98))
  root.style.setProperty('--group-job-bg', toRgba(lightGroupJob, 0.98))
  root.style.setProperty('--group-normal-bg', toRgba(lightGroupNormal, 0.98))
  root.style.setProperty('--group-hover-bg', toRgba(lightGroupHover, 0.98))
  root.style.setProperty('--state-ok-bg', 'rgba(32, 136, 86, 0.2)')
  root.style.setProperty('--state-ok-text', '#1c8152')
  root.style.setProperty('--state-ng-bg', 'rgba(191, 71, 71, 0.18)')
  root.style.setProperty('--state-ng-text', '#aa3737')
  root.style.setProperty('--state-unknown-bg', 'rgba(92, 111, 150, 0.2)')
  root.style.setProperty('--state-unknown-text', '#44608f')
  root.style.setProperty('--state-running-bg', 'rgba(176, 133, 39, 0.2)')
  root.style.setProperty('--state-running-text', '#8b6708')
  root.style.setProperty('--state-unreachable-bg', 'rgba(155, 73, 101, 0.18)')
  root.style.setProperty('--state-unreachable-text', '#8f3556')
  root.style.setProperty('--state-total-bg', 'rgba(102, 132, 183, 0.2)')
  root.style.setProperty('--state-total-text', '#426394')
  root.style.setProperty('--chart-axis-line', toRgba(mixHex('#95b2de', selectedTheme.primary, 0.3), 0.62))
  root.style.setProperty('--chart-axis-text', mixHex('#5f78a8', selectedTheme.primaryStrong, 0.22))
  root.style.setProperty('--chart-grid-line', toRgba(mixHex('#a8c0e5', selectedTheme.primary, 0.25), 0.36))
  root.style.setProperty('--chart-plot-bg', toRgba(lightSurfaceStrong, 0.92))
  root.style.setProperty('--chart-avg-line', 'rgba(39, 153, 99, 0.82)')
  root.style.setProperty('--chart-avg-bg', toRgba(lightSurfaceMuted, 0.96))
  root.style.setProperty('--chart-avg-border', 'rgba(39, 153, 99, 0.4)')
  root.style.setProperty('--chart-avg-text', '#1f8a5b')
  root.style.setProperty('--chart-bar-bg', mixHex('#3f82e8', selectedTheme.primary, 0.75))
  root.style.setProperty('--chart-bar-shadow', toRgba(mixHex('#2f65b8', selectedTheme.primaryStrong, 0.38), 0.28))
  root.style.setProperty('--timeline-axis-line', toRgba(mixHex('#95b2de', selectedTheme.primary, 0.3), 0.56))
  root.style.setProperty('--timeline-axis-text', mixHex('#5f78a8', selectedTheme.primaryStrong, 0.22))
  root.style.setProperty('--timeline-day-border', toRgba(mixHex('#95b2de', selectedTheme.primary, 0.3), 0.62))
  root.style.setProperty('--timeline-day-title', '#2a4573')
  root.style.setProperty('--timeline-day-date', mixHex('#3d679f', selectedTheme.primary, 0.32))
  root.style.setProperty('--timeline-column-bg', toRgba(lightTimelineColumn, 0.95))
  root.style.setProperty('--timeline-hour-line', toRgba(mixHex('#95b2de', selectedTheme.primary, 0.3), 0.42))
  root.style.setProperty('--timeline-event-bg', lightTimelineEvent)
  root.style.setProperty('--timeline-event-text', '#f5f9ff')
  root.style.setProperty('--timeline-event-shadow', toRgba(mixHex('#2a5799', selectedTheme.primaryStrong, 0.3), 0.28))
  root.style.setProperty('--mobile-nav-bg-start', toRgba(lightBase, 0.9))
  root.style.setProperty('--mobile-nav-bg-end', toRgba(lightSoft, 0.72))
  root.style.setProperty('--mobile-nav-border', toRgba(lightLine, 0.52))
  root.style.setProperty('--mobile-nav-text', mixHex('#4f6691', selectedTheme.primaryStrong, 0.2))
  root.style.setProperty('--mobile-nav-text-active', mixHex('#1a2f55', selectedTheme.primaryStrong, 0.18))
  root.style.setProperty('--mobile-nav-icon-filter', 'brightness(0) saturate(100%) invert(31%) sepia(18%) saturate(780%) hue-rotate(182deg) brightness(93%) contrast(88%)')
  root.style.setProperty('--mobile-nav-icon-active-filter', 'brightness(0) saturate(100%) invert(19%) sepia(27%) saturate(909%) hue-rotate(183deg) brightness(92%) contrast(90%)')
  root.style.setProperty('--header-settings-icon-filter', 'brightness(0) saturate(100%) invert(19%) sepia(27%) saturate(909%) hue-rotate(183deg) brightness(92%) contrast(90%)')
  root.style.setProperty('--mobile-register-bg-start', toRgba(lightSurfaceStrong, 0.94))
  root.style.setProperty('--mobile-register-bg-end', toRgba(lightSurfaceMuted, 0.8))
  root.style.setProperty('--mobile-register-border', toRgba(lightLine, 0.72))
  root.style.setProperty('--mobile-register-active-start', mixHex(selectedTheme.primary, '#4d8fff', 0.25))
  root.style.setProperty('--mobile-register-active-end', mixHex(selectedTheme.primaryStrong, selectedTheme.accent, 0.2))
  root.style.setProperty('--mobile-register-active-shadow', toRgba(selectedTheme.primary, 0.26))
  root.style.setProperty('--scrollbar-track', toRgba(lightSurfaceMuted, 0.94))
  root.style.setProperty('--scrollbar-thumb', toRgba(mixHex('#7b9fd4', selectedTheme.primary, 0.32), 0.8))
  root.style.setProperty('--scrollbar-thumb-hover', toRgba(mixHex('#5d86c2', selectedTheme.primaryStrong, 0.24), 0.9))
}
